services:
  postgres:
    image: postgres:16-alpine
    container_name: login_roles_postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-login_roles_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - login_roles_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-login_roles_db}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: login_roles_pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - login_roles_network
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login_roles_backend
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432/${POSTGRES_DB:-login_roles_db}
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
      AUTH_REQUIRED: ${AUTH_REQUIRED:-true}
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-key-sesion07-r18}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules
    networks:
      - login_roles_network
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Esperando a PostgreSQL...' &&
        npx prisma migrate deploy &&
        echo 'Migraciones aplicadas' &&
        npx prisma db seed &&
        echo 'Seed ejecutado' &&
        npm run dev
      "

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  login_roles_network:
    driver: bridge
